server:
  port: 8040

spring:
  application:
    name: lemon-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
#  instance:
    #    prefer-ip-address: true
    #    instance-id: ${spring.application.name}:${server.port}
    #    health-check-url-path: /actuator/health
    #   status-page-url-path: /actuator/info
    #   lease-expiration-duration-in-seconds: 5
#    lease-renewal-interval-in-seconds: 5


zuul:
  ignored-services: '*'
  routes:
    lemon-iam:
      path: /iam/**
      service-id: lemon-iam
      #转发时带上路径
      stripPrefix: false

ribbon:
  eureka:
    enabled: false