server:
  port: 8761

#spring-cloud-starter-netflix-eureka-server and spring-cloud-starter-netflix-eureka-client
#come along with a spring-cloud-starter-netflix-ribbon. Since Ribbon load-balancer
#is now in maintenance mode, we suggest switching to using the
#Spring Cloud LoadBalancer, also included in Eureka starters, instead.
spring:
  application:
    name: lemon-eureka
  cloud:
    #禁用Ribbon使用Spring Cloud LoadBalancer
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    hostname: localhost
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    #不注册自己
    registerWithEureka: false
    #是否从eureka获取注册信息（集群视需要设置为true以同步节点间的注册数据）
    fetchRegistry: false
    service-url:
      #交互地址，多个时,用逗号隔开
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    #是否开启自我保护，生产环境设置true  测试环境看需要设置未false
    enable-self-preservation: true
    #检测间隔
    eviction-interval-timer-in-ms: 5000