server:
  port: 8762

spring:
  application:
    name: lemon-eureka-peer2
  profiles: peer2
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
