server:
  port: 8761

spring:
  application:
    name: lemon-eureka-peer1
  profiles: peer1
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
