server:
  port: 8511

spring:
  application:
    name: consul-iam
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consul-iam
      #healthCheckPath:
      #healthCheckInterval

